In [25]:
import pandas as pd
from sklearn.preprocessing import StandardScaler


df= pd.read_csv('Dataset of Diabetes .csv')

df=df.dropna(thresh=10)
#df=df.fillna(df.mean(numeric_only=True), inplace=True)
df.head()
cols_to_scale = ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']

stdScaler= StandardScaler()

df[cols_to_scale]=stdScaler.fit_transform(df[cols_to_scale])
df.head()

df['Gender']= df['Gender'].apply(lambda x: 0 if x=='M' else 1)
df['CLASS'] = df['CLASS'].map({'N': 0, 'Pre-diabetic': 1, 'Y': 2})

   

df.head()

clean_data= df.drop(columns=['ID', 'No_Pation'])

clean_data.head()
clean_data.iloc[230:300]

,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
230,0,-0.173738,-0.724254,-0.149162,-0.505840,-0.816871,0.607215,-0.613180,-0.816289,-0.124175,0.689928,2.0
231,1,0.281074,1.150513,0.384573,-1.019119,-0.048283,-0.463850,0.144300,0.170662,-0.315340,1.093162,2.0
232,0,0.281074,-0.587908,-0.416030,-1.374466,-0.586295,-0.606658,-0.613180,-0.816289,-0.124175,1.899629,2.0
233,0,-0.287441,0.741473,-0.065766,-0.505840,-0.816871,1.035641,-0.310188,-1.354626,-0.042247,0.286695,2.0
234,1,0.622183,-0.451561,0.367894,-0.900670,-0.509436,-0.249637,1.659260,-1.534071,-0.124175,1.698012,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
295,0,0.167371,-0.758341,-0.416030,0.599684,-0.586295,-0.963680,-0.158692,-0.457398,-0.369958,-0.116538,2.0
296,0,0.281074,-0.656081,-0.599502,-0.584806,0.028576,0.107385,-1.067668,0.708998,-0.206103,0.488312,2.0
297,0,0.167371,0.093826,0.267819,0.560201,0.259153,-0.392445,0.144300,0.529553,-0.288030,0.085078,2.0
298,0,0.281074,-0.656081,-0.599502,-0.584806,0.028576,0.107385,-1.067668,0.708998,-0.206103,0.488312,2.0
299,0,0.167371,0.093826,0.267819,0.560201,0.259153,-0.392445,0.144300,0.529553,-0.288030,0.085078,2.0